---
DOMAIN_NAME: "LOCAL"
LOG_BUFFER_SIZE: 65536
ENABLE_SECRET: cisco
USER_LOCAL_NAME: cisco 
USER_LOCAL_PASS: cisco
#TODO: Set only for STP root
STP_PRIORITY: 4096
INT_MGMT: "Vlan 1"
INT_MGMT_IP_SUBNETMASK: "255.255.255.0"
SSH_TIMEOUT: 60
ACL_SNMP: "ACL_SNMP"
MONITORING_SERVER: "1.2.3.4"
ACL_VTY: "ACL_VTY_IN"
MANAGEMENT_SERVER: "2.3.4.5"
LOGGING_SERVER: "3.4.5.6"
SNMP_V3_GROUP: "SNMP_V3_GROUP"
SNMP_V3_USER: "SNMP_V3_USER"
SNMP_V3_AUTH_PASS: "SNMP_V3_AUTH_PASS"
SNMP_V3_PRIV_PASS: "SNMP_V3_PRIV_PASS"
BANNER_EXEC: "BANNER-EXEC"
BANNER_INCOMING: "BANNER-INCOMING"
BANNER_LOGIN: "BANNER-LOGIN"
BANNER_MOTD: "BANNER-MOTD"
LINE_EXEC_TIMEOUT: "10 0"
NTP_SERVER: "4.5.6.7"
#TODO: NTP ACL
